#pragma once

/// A pairing heap (jemalloc: `ph.h`), ported bit-for-bit: the tree shape decides e.g. which non-full slab becomes
/// `current_slab` and which extent the enumerate search of `extent_set` finds first.
///
/// "The Pairing Heap: A New Form of Self-Adjusting Heap", with the auxiliary twopass list from "Pairing Heaps:
/// Experiments and Analysis", and jemalloc's optimization: after N insertions since the last aux-list merge, do
/// ffs(N) pop-and-link operations on the aux list (which keeps it O(log N) long and moves linking onto inserters).
///
/// Node relations: `left_child` is the leftmost child; children form a doubly-linked sibling list via `next`/`prev`, the
/// first child's `prev` points to its parent. The aux list is the sibling list hanging off `root->next`.
///
///     struct Node
///     {
///         uint64_t key;
///         PairingHeapLink<Node> link;
///     };
///     struct NodeCompare
///     {
///         int operator()(const Node * a, const Node * b) const { return (a->key > b->key) - (a->key < b->key); }
///     };
///     using NodeHeap = PairingHeap<Node, &Node::link, NodeCompare>;
///
/// `Compare` is a stateless callable returning a negative value when `a` has higher priority (is closer to the root).

#include <allocator/Common.h>

namespace jemalloc
{

/// jemalloc: phn_link_t
template <typename T>
struct PairingHeapLink
{
    T * prev;
    T * next;
    T * left_child;
};

/// jemalloc: ph_enumerate_vars_t
struct PairingHeapEnumerateVariables
{
    uint16_t front;
    uint16_t rear;
    uint16_t queue_size;
    uint16_t visited_num;
    uint16_t max_visit_num;
    uint16_t max_queue_size;
};

/// The BFS queue for `enumeratePrepare`/`enumerateNext` (jemalloc: `<prefix>_enumerate_helper_t` from `ph_structs`).
template <typename T, size_t max_queue_size_>
struct PairingHeapEnumerateHelper
{
    static constexpr size_t capacity = max_queue_size_;
    T * bfs_queue[max_queue_size_];
    PairingHeapEnumerateVariables variables;
};

/// jemalloc: ph_t + the functions generated by `ph_gen`
template <typename T, PairingHeapLink<T> T::* link, typename Compare>
class PairingHeap
{
public:
    template <size_t max_queue_size>
    using EnumerateHelper = PairingHeapEnumerateHelper<T, max_queue_size>;

    constexpr PairingHeap() = default;

    PairingHeap(const PairingHeap &) = delete;
    PairingHeap & operator=(const PairingHeap &) = delete;

    /// jemalloc: ph_new
    ALLOCATOR_ALWAYS_INLINE void init()
    {
        root = nullptr;
        auxiliary_count = 0;
    }

    /// jemalloc: ph_empty
    ALLOCATOR_ALWAYS_INLINE bool empty() const { return root == nullptr; }

    /// The minimum. Mutates the structure (merges the aux list).
    /// jemalloc: ph_first
    ALLOCATOR_ALWAYS_INLINE T * first()
    {
        if (root == nullptr)
            return nullptr;
        mergeAuxiliary();
        return root;
    }

    /// Some element, without mutation: the first of the aux list if any, otherwise the root.
    /// jemalloc: ph_any
    ALLOCATOR_ALWAYS_INLINE T * any() const
    {
        if (root == nullptr)
            return nullptr;
        T * auxiliary = getNext(root);
        if (auxiliary != nullptr)
            return auxiliary;
        return root;
    }

    /// jemalloc: ph_insert
    ALLOCATOR_ALWAYS_INLINE void insert(T * node)
    {
        linkInit(node);

        /// Treat the root as an aux list during insertion, and lazily merge during `removeFirst`.
        if (root == nullptr)
        {
            root = node;
            return;
        }

        /// As a special case, check to see if we can replace the root.
        if (compare(node, root) < 0)
        {
            setLeftChild(node, root);
            setPrev(root, node);
            root = node;
            auxiliary_count = 0;
            return;
        }

        setNext(node, getNext(root));
        if (getNext(root) != nullptr)
            setPrev(getNext(root), node);
        setPrev(node, root);
        setNext(root, node);

        ++auxiliary_count;
        unsigned num_merges = findFirstSet(auxiliary_count);
        bool done = false;
        for (unsigned i = 0; i < num_merges && !done; ++i)
            done = tryAuxiliaryMergePair();
    }

    /// jemalloc: ph_remove_first
    ALLOCATOR_ALWAYS_INLINE T * removeFirst()
    {
        if (root == nullptr)
            return nullptr;
        mergeAuxiliary();
        T * result = root;
        root = mergeChildren(root);
        return result;
    }

    /// jemalloc: ph_remove
    ALLOCATOR_ALWAYS_INLINE void remove(T * node)
    {
        if (root == node)
        {
            mergeAuxiliary();
            root = mergeChildren(node);
            return;
        }

        T * prev = getPrev(node);
        T * next = getNext(node);

        /// If we have children, then we integrate them back in the heap.
        T * replace = mergeChildren(node);
        if (replace != nullptr)
        {
            setNext(replace, next);
            if (next != nullptr)
                setPrev(next, replace);
            next = replace;
        }

        if (next != nullptr)
            setPrev(next, prev);

        ALLOCATOR_ASSERT(prev != nullptr);
        if (getLeftChild(prev) == node)
            setLeftChild(prev, next);
        else
            setNext(prev, next);
    }

    /// jemalloc: <prefix>_remove_any
    ALLOCATOR_ALWAYS_INLINE T * removeAny()
    {
        T * result = any();
        if (result != nullptr)
            remove(result);
        return result;
    }

    /// Prepares a BFS enumeration of at most `max_visit_num` nodes. The heap must not be modified until the
    /// enumeration ends. Must be called on a non-empty heap: jemalloc pushes the root unconditionally.
    /// jemalloc: ph_enumerate_prepare
    template <size_t N>
    ALLOCATOR_ALWAYS_INLINE void enumeratePrepare(EnumerateHelper<N> & helper, uint16_t max_visit_num, uint16_t max_queue_size) const
    {
        ALLOCATOR_ASSERT(max_queue_size <= N);
        enumerateVariablesInit(helper.variables, max_visit_num, max_queue_size);
        enumerateQueuePush(root, helper.bfs_queue, helper.variables);
    }

    /// The next element of the enumeration, or null when it ends (then it must not be called again).
    /// jemalloc: ph_enumerate_next
    template <size_t N>
    ALLOCATOR_ALWAYS_INLINE T * enumerateNext(EnumerateHelper<N> & helper) const
    {
        PairingHeapEnumerateVariables & variables = helper.variables;
        if (variables.queue_size == 0)
            return nullptr;

        ++variables.visited_num;
        if (variables.visited_num > variables.max_visit_num)
            return nullptr;

        T * result = enumerateQueuePop(helper.bfs_queue, variables);
        ALLOCATOR_ASSERT(result != nullptr);
        T * left = getLeftChild(result);
        T * right = getNext(result);
        if (left)
            enumerateQueuePush(left, helper.bfs_queue, variables);
        if (right)
            enumerateQueuePush(right, helper.bfs_queue, variables);
        return result;
    }

    /// Direct access for debugging and tests.
    T * rootNode() const { return root; }
    size_t auxiliaryCount() const { return auxiliary_count; }

private:
    T * root = nullptr;
    /// Inserts done since the last aux-list merge (not necessarily the size of the aux list).
    size_t auxiliary_count = 0;

    ALLOCATOR_ALWAYS_INLINE static int compare(T * a, T * b) { return Compare{}(a, b); }

    /// jemalloc: phn_link_init
    ALLOCATOR_ALWAYS_INLINE static void linkInit(T * node)
    {
        (node->*link).prev = nullptr;
        (node->*link).next = nullptr;
        (node->*link).left_child = nullptr;
    }

    /// jemalloc: phn_lchild_get, phn_lchild_set, phn_next_get, phn_next_set, phn_prev_get, phn_prev_set
    ALLOCATOR_ALWAYS_INLINE static T * getLeftChild(const T * node) { return (node->*link).left_child; }
    ALLOCATOR_ALWAYS_INLINE static void setLeftChild(T * node, T * left_child) { (node->*link).left_child = left_child; }
    ALLOCATOR_ALWAYS_INLINE static T * getNext(const T * node) { return (node->*link).next; }
    ALLOCATOR_ALWAYS_INLINE static void setNext(T * node, T * next) { (node->*link).next = next; }
    ALLOCATOR_ALWAYS_INLINE static T * getPrev(const T * node) { return (node->*link).prev; }
    ALLOCATOR_ALWAYS_INLINE static void setPrev(T * node, T * prev) { (node->*link).prev = prev; }

    /// `node1` becomes the new leftmost child of `node0`; requires cmp(phn0, phn1) <= 0.
    /// jemalloc: phn_merge_ordered
    ALLOCATOR_ALWAYS_INLINE static void mergeOrdered(T * node0, T * node1)
    {
        ALLOCATOR_ASSERT(node0 != nullptr);
        ALLOCATOR_ASSERT(node1 != nullptr);
        ALLOCATOR_ASSERT(compare(node0, node1) <= 0);

        setPrev(node1, node0);
        T * node0_child = getLeftChild(node0);
        setNext(node1, node0_child);
        if (node0_child != nullptr)
            setPrev(node0_child, node1);
        setLeftChild(node0, node1);
    }

    /// Ties go to `node1`.
    /// jemalloc: phn_merge
    ALLOCATOR_ALWAYS_INLINE static T * merge(T * node0, T * node1)
    {
        T * result;
        if (node0 == nullptr)
        {
            result = node1;
        }
        else if (node1 == nullptr)
        {
            result = node0;
        }
        else if (compare(node0, node1) < 0)
        {
            mergeOrdered(node0, node1);
            result = node0;
        }
        else
        {
            mergeOrdered(node1, node0);
            result = node1;
        }
        return result;
    }

    /// Multipass merge, wherein the first two elements of a FIFO are repeatedly merged, and each result is appended
    /// to the singly linked FIFO, until the FIFO contains only a single element. We start with a sibling list but no
    /// reference to its tail, so we do a single pass over the sibling list to populate the FIFO.
    /// jemalloc: phn_merge_siblings
    ALLOCATOR_ALWAYS_INLINE static T * mergeSiblings(T * node)
    {
        T * head = nullptr;
        T * tail = nullptr;
        T * node0 = node;
        T * node1 = getNext(node0);

        if (node1 == nullptr)
            return node0;

        T * rest = getNext(node1);
        if (rest != nullptr)
            setPrev(rest, nullptr);
        setPrev(node0, nullptr);
        setNext(node0, nullptr);
        setPrev(node1, nullptr);
        setNext(node1, nullptr);
        node0 = merge(node0, node1);
        head = tail = node0;
        node0 = rest;
        while (node0 != nullptr)
        {
            node1 = getNext(node0);
            if (node1 != nullptr)
            {
                rest = getNext(node1);
                if (rest != nullptr)
                    setPrev(rest, nullptr);
                setPrev(node0, nullptr);
                setNext(node0, nullptr);
                setPrev(node1, nullptr);
                setNext(node1, nullptr);
                node0 = merge(node0, node1);
                setNext(tail, node0);
                tail = node0;
                node0 = rest;
            }
            else
            {
                setNext(tail, node0);
                tail = node0;
                node0 = nullptr;
            }
        }
        node0 = head;
        node1 = getNext(node0);
        if (node1 != nullptr)
        {
            while (true)
            {
                head = getNext(node1);
                ALLOCATOR_ASSERT(getPrev(node0) == nullptr);
                setNext(node0, nullptr);
                ALLOCATOR_ASSERT(getPrev(node1) == nullptr);
                setNext(node1, nullptr);
                node0 = merge(node0, node1);
                if (head == nullptr)
                    break;
                setNext(tail, node0);
                tail = node0;
                node0 = head;
                node1 = getNext(node0);
            }
        }

        return node0;
    }

    /// jemalloc: ph_merge_aux
    ALLOCATOR_ALWAYS_INLINE void mergeAuxiliary()
    {
        auxiliary_count = 0;
        T * node = getNext(root);
        if (node != nullptr)
        {
            setPrev(root, nullptr);
            setNext(root, nullptr);
            setPrev(node, nullptr);
            node = mergeSiblings(node);
            ALLOCATOR_ASSERT(getNext(node) == nullptr);
            mergeOrdered(root, node);
        }
    }

    /// jemalloc: ph_merge_children
    ALLOCATOR_ALWAYS_INLINE static T * mergeChildren(T * node)
    {
        T * left_child = getLeftChild(node);
        if (left_child == nullptr)
            return nullptr;
        return mergeSiblings(left_child);
    }

    /// Returns true if we should stop trying to merge.
    /// jemalloc: ph_try_aux_merge_pair
    ALLOCATOR_ALWAYS_INLINE bool tryAuxiliaryMergePair()
    {
        ALLOCATOR_ASSERT(root != nullptr);
        T * node0 = getNext(root);
        if (node0 == nullptr)
            return true;
        T * node1 = getNext(node0);
        if (node1 == nullptr)
            return true;
        T * next_node1 = getNext(node1);
        setNext(node0, nullptr);
        setPrev(node0, nullptr);
        setNext(node1, nullptr);
        setPrev(node1, nullptr);
        node0 = merge(node0, node1);
        setNext(node0, next_node1);
        if (next_node1 != nullptr)
            setPrev(next_node1, node0);
        setNext(root, node0);
        setPrev(node0, root);
        return next_node1 == nullptr;
    }

    /// jemalloc: ph_enumerate_vars_init
    ALLOCATOR_ALWAYS_INLINE static void
    enumerateVariablesInit(PairingHeapEnumerateVariables & variables, uint16_t max_visit_num, uint16_t max_queue_size)
    {
        variables.queue_size = 0;
        variables.visited_num = 0;
        variables.front = 0;
        variables.rear = 0;
        variables.max_visit_num = max_visit_num;
        variables.max_queue_size = max_queue_size;
        ALLOCATOR_ASSERT(variables.max_visit_num > 0);
        /// The queue must not overflow before reaching max_visit_num.
        ALLOCATOR_ASSERT(variables.max_queue_size >= (variables.max_visit_num + 1) / 2);
    }

    /// jemalloc: ph_enumerate_queue_push
    ALLOCATOR_ALWAYS_INLINE static void enumerateQueuePush(T * node, T ** bfs_queue, PairingHeapEnumerateVariables & variables)
    {
        /// jemalloc compatibility: jemalloc asserts `queue_size < max_queue_size`, but its own precondition
        /// (max_queue_size >= (max_visit_num + 1) / 2) does not guarantee it: the queue grows by at most one per visit,
        /// so with `extent_set`'s parameters (32, 32) it can overflow while processing the last visit. Then the push
        /// overwrites the queue front, which is never popped because the visit limit is reached, so it is harmless.
        /// jemalloc never enables assertions in ClickHouse; we keep the assertion only for the harmful cases.
        ALLOCATOR_ASSERT(variables.queue_size < variables.max_queue_size || variables.visited_num == variables.max_visit_num);
        bfs_queue[variables.rear] = node;
        variables.rear = static_cast<uint16_t>((variables.rear + 1) % variables.max_queue_size);
        ++variables.queue_size;
    }

    /// jemalloc: ph_enumerate_queue_pop
    ALLOCATOR_ALWAYS_INLINE static T * enumerateQueuePop(T ** bfs_queue, PairingHeapEnumerateVariables & variables)
    {
        ALLOCATOR_ASSERT(variables.queue_size > 0);
        ALLOCATOR_ASSERT(variables.queue_size <= variables.max_queue_size);
        T * result = bfs_queue[variables.front];
        variables.front = static_cast<uint16_t>((variables.front + 1) % variables.max_queue_size);
        --variables.queue_size;
        return result;
    }
};

}
